In [1]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.2-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 5.4 MB/s  0:00:01 eta 0:00:01
Downloading numpy-2.4.2-cp314-cp314-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 10.4 MB/s  0:00:00 eta 0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.2 pandas-3.0.0

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install numpy matplotlib seaborn

Requirement already satisfied: numpy in ./.venv/lib/python3.14/site-packages (2.4.2)
Collecting matplotlib
  Downloading matplotlib-3.10.8-cp314-cp314-macosx_11_0_arm64.whl.metadata (52 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.61.1-cp314-cp314-macosx_10_15_universal2.whl.metadata (114 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.9-cp314-cp314-macosx_11_0_arm64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in ./.venv/lib/python3.14/site-packages (from seaborn) (3.0.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.8-cp314-cp314-macosx_11_0_arm64.whl (8.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 13.8 MB/s  0:00:00 eta 0:00:01
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading contourpy-1.3.3-cp314-cp314-macosx_11_0_arm64.whl (273 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.1-cp314-cp314-macosx_10_15_universal2.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 18.2 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp314-cp314-macosx_11_0_arm64.whl (64 kB)
Downloading pillow-12.1.0-cp314-cp314-macosx_11_0_arm64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 17.8 MB/s  0:00:00 eta 0:00:01
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [seaborn]m7/8 [seaborn]ib]
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.1 kiwisolver-1.4.9 matplotlib-3.10.8 pillow-12.1.0 pyparsing-3.3.2 seaborn-0.13.2

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [69]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in ./.venv/lib/python3.14/site-packages (from scikit-learn) (2.4.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.0-cp314-cp314-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-macosx_12_0_arm64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 6.5 MB/s  0:00:01 eta 0:00:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.0-cp314-cp314-macosx_14_0_arm64.whl (20.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.1/20.1 MB 8.2 MB/s  0:00:02 eta 0:00:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.0 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [4]:
df = pd.read_csv('online_retail_II.csv')

# Data cleaning steps
## 1. Understand the data

> ```python
> df.head()
> df.info()
> df.describe()
> df.shape
> ```

---

## 2. Handle missing values

**Detect**

> ```python
> df.isnull().sum()
> ```

**Drop**

> ```python
> df.dropna()                      # drop rows
> df.dropna(axis=1)                # drop columns
> ```

**Impute**

> ```python
> df["age"].fillna(df["age"].mean(), inplace=True)
> df["city"].fillna(df["city"].mode()[0], inplace=True)
> ```

**Sklearn imputer**

> ```python
> from sklearn.impute import SimpleImputer
> 
> imputer = SimpleImputer(strategy="median")
> df[["salary"]] = imputer.fit_transform(df[["salary"]])
> ```

---

## 3. Remove duplicates

> ```python
> df.duplicated().sum()
> df = df.drop_duplicates()
> ```

---

## 4. Fix data types

> ```python
> df["age"] = df["age"].astype(int)
> df["date"] = pd.to_datetime(df["date"])
> ```

---

## 5. Handle inconsistent values

> ```python
> df["city"] = df["city"].str.lower().str.strip()
> 
> df["city"] = df["city"].replace({
>     "ny": "new york",
>     "nyc": "new york"
> })
> ```

---

**Capping**

> ```python
> df["income"] = df["income"].clip(lower=0, upper=200000)
> ```

---

## 6. Feature engineering

Cleaning alone is not enough.

Examples:

* Total transaction value
* RFM features
* Time-based features

```python
df["TotalAmount"] = df["Quantity"] * df["Price"]
```

This is a **must-have step** in ML pipelines.

---

## 7. Handle skew / transformation

Even if you skip “outlier handling”, you should:

* Log-transform
* Use robust scaling

```python
df["income"] = np.log1p(df["income"])
```

(Or later at feature level.)

---

## 8. Feature scaling

**Standardization**

> ```python
> from sklearn.preprocessing import StandardScaler
> 
> scaler = StandardScaler()
> df[["age", "income"]] = scaler.fit_transform(df[["age", "income"]])
> ```

**Normalization**

> ```python
> from sklearn.preprocessing import MinMaxScaler
> 
> scaler = MinMaxScaler()
> df[["age", "income"]] = scaler.fit_transform(df[["age", "income"]])
> ```

# Understand Data

In [5]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  str
 1   StockCode    1067371 non-null  str
 2   Description  1062989 non-null  str
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  str
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 65.1 MB

In [8]:
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [7]:
df.shape

(1067371, 8)

# Handling Missing Values

In [9]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

I don't need the description so I am going to drop description column.

For customer segmentation and churn analysis, I removed transactions with missing Customer ID because churn and behavioral metrics require customer-level tracking. Anonymous purchases cannot be reliably modeled.

In [11]:
df = df.drop(columns="Description")

In [12]:
df = df.dropna(subset=["Customer ID"])

In [13]:
df.isnull().sum()

Invoice        0
StockCode      0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

# Remove duplicates

If invoice, product (StockCode), quantity, and timestamp (InvoiceDate) are identical, I treat the row as a duplicate because it represents the same line item being recorded more than once.

In [18]:
df.duplicated(subset=["Invoice", "StockCode", "Quantity", "InvoiceDate"]).sum()

np.int64(26562)

In [19]:
df = df.drop_duplicates(
    subset=["Invoice", "StockCode", "Quantity", "InvoiceDate"],
    keep="first"
)

# Fix data types

In [20]:
df.dtypes

Invoice            str
StockCode          str
Quantity         int64
InvoiceDate        str
Price          float64
Customer ID    float64
Country            str
dtype: object

Let's converted date fields to datetime and treated identifiers as categorical variables to avoid misleading numerical operations.

In [21]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [23]:
df["Customer ID"] = df["Customer ID"].astype("int").astype("str")

In [24]:
df["Country"] = df["Country"].astype("category")

In [25]:
df.dtypes

Invoice                   str
StockCode                 str
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID               str
Country              category
dtype: object

# Handle Inconsistent Values

In [29]:
df["Country"].value_counts()

Country
United Kingdom          716048
Germany                  17335
EIRE                     16014
France                   13897
Netherlands               5137
Spain                     3754
Belgium                   3110
Switzerland               3058
Portugal                  2414
Australia                 1890
Channel Islands           1646
Italy                     1507
Sweden                    1343
Norway                    1304
Cyprus                    1157
Finland                   1049
Austria                    938
Denmark                    797
Greece                     663
Japan                      565
USA                        535
Poland                     527
Unspecified                521
United Arab Emirates       386
Singapore                  338
Israel                     321
Malta                      299
Canada                     228
Iceland                    222
Lithuania                  154
RSA                        123
Brazil                      94
Thailand                    76
Korea                       63
European Community          61
Bahrain                     59
West Indies                 54
Lebanon                     45
Czech Republic              30
Nigeria                     30
Saudi Arabia                10
Name: count, dtype: int64

No extra spaces, different casing, same country misspelled found in country name.

In [34]:
df[df["Price"] <= 0]

,Invoice,StockCode,Quantity,InvoiceDate,Price,Customer ID,Country
4674,489825,22076,12,2009-12-02 13:34:00,0.0,16126,United Kingdom
6781,489998,48185,2,2009-12-03 11:19:00,0.0,15658,United Kingdom
16107,490727,M,1,2009-12-07 16:38:00,0.0,17231,United Kingdom
18738,490961,22065,1,2009-12-08 15:25:00,0.0,14108,United Kingdom
18739,490961,22142,12,2009-12-08 15:25:00,0.0,14108,United Kingdom
...,...,...,...,...,...,...,...
979925,575579,22089,24,2011-11-10 11:49:00,0.0,13081,United Kingdom
1004540,577129,22464,4,2011-11-17 19:52:00,0.0,15602,United Kingdom
1005014,577168,M,1,2011-11-18 10:42:00,0.0,12603,Germany
1011446,577696,M,1,2011-11-21 11:57:00,0.0,16406,United Kingdom
1027583,578841,84826,12540,2011-11-25 15:57:00,0.0,13256,United Kingdom

Negative or zero price is free item, correction, or error. So we will remove it.

In [35]:
df = df[df["Price"] > 0]

In [36]:
df[df["Quantity"] <= 0]

,Invoice,StockCode,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,-12,2009-12-01 10:33:00,2.95,16321,Australia
179,C489449,85206A,-6,2009-12-01 10:33:00,1.65,16321,Australia
180,C489449,21895,-4,2009-12-01 10:33:00,4.25,16321,Australia
181,C489449,21896,-6,2009-12-01 10:33:00,2.10,16321,Australia
182,C489449,22083,-12,2009-12-01 10:33:00,2.95,16321,Australia
...,...,...,...,...,...,...,...
1065910,C581490,23144,-11,2011-12-09 09:57:00,0.83,14397,United Kingdom
1067002,C581499,M,-1,2011-12-09 10:28:00,224.69,15498,United Kingdom
1067176,C581568,21258,-5,2011-12-09 11:57:00,10.95,15311,United Kingdom
1067177,C581569,84978,-1,2011-12-09 11:58:00,1.25,17315,United Kingdom
1067178,C581569,20979,-5,2011-12-09 11:58:00,1.25,17315,United Kingdom

Negative or zero quantity means item is return, error, or correction

In [37]:
df = df[df["Quantity"] > 0]

In [38]:
df["StockCode"].unique()[:20]

<StringArray>
[ '85048', '79323P', '79323W',  '22041',  '21232',  '22064',  '21871',
  '21523',  '22350',  '22349',  '22195',  '22353', '48173C',  '21755',
  '21754',  '84879',  '22119',  '22142',  '22296',  '22295']
Length: 20, dtype: str

I found that in stock code post mean postage, D mean discount, M mean manual adjustment so they need to remove.

In [45]:
df = df[~df["StockCode"].isin(['POST', 'D', 'M'])]

In invoice start with C are cancelled items. So need to remove.

In [46]:
df = df[~df["Invoice"].str.startswith('C')]

# Feature engineering

Add new column Total Amount.

In [55]:
df["TotalAmount"] = df["Quantity"] * df["Price"]

Reference Date one day after the last transaction

In [57]:
reference_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)

RFM table

In [59]:
rfm = df.groupby("Customer ID").agg({
    "InvoiceDate": lambda x: (reference_date - x.max()).days,
    "Invoice": "nunique",
    "TotalAmount": "sum"
})
rfm.columns = ["Recency", "Frequency", "Monetary"]

In [60]:
rfm.head()

             Recency  Frequency  Monetary
Customer ID
12346            326         12  77556.46
12347              2          8   4921.53
12348             75          5   1658.40
12349             19          3   3678.69
12350            310          1    294.40

In [62]:
rfm.describe()

           Recency    Frequency       Monetary
count  5862.000000  5862.000000    5862.000000
mean    200.867793     6.256397    2916.603845
std     209.095351    12.807525   14336.064571
min       1.000000     1.000000       2.950000
25%      26.000000     1.000000     338.725000
50%      95.500000     3.000000     855.220000
75%     379.000000     7.000000    2237.032500
max     739.000000   379.000000  580987.040000

In [63]:
rfm.shape

(5862, 3)

# Handle skew & transform RFM features

Check skewness

In [64]:
rfm.skew()

Recency       0.891494
Frequency    12.160103
Monetary     25.275094
dtype: float64

Apply log transformation

In [65]:
rfm_transformed = rfm.copy()

rfm_transformed["Recency"] = np.log1p(rfm_transformed["Recency"])
rfm_transformed["Frequency"] = np.log1p(rfm_transformed["Frequency"])
rfm_transformed["Monetary"] = np.log1p(rfm_transformed["Monetary"])

In [66]:
rfm_transformed.describe()

           Recency    Frequency     Monetary
count  5862.000000  5862.000000  5862.000000
mean      4.451360     1.546736     6.805091
std       1.559345     0.808267     1.383228
min       0.693147     0.693147     1.373716
25%       3.295837     0.693147     5.828136
50%       4.569530     1.386294     6.752527
75%       5.940171     2.079442     7.713352
max       6.606650     5.940171    13.272485

In [67]:
rfm_transformed.skew()

Recency     -0.487178
Frequency    1.002850
Monetary     0.267400
dtype: float64

# Feature Scaling

In [70]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

rfm_scaled = scaler.fit_transform(
    rfm_transformed[["Recency", "Frequency", "Monetary"]]
)

In [71]:
rfm_scaled = pd.DataFrame(
    rfm_scaled,
    columns=["Recency", "Frequency", "Monetary"],
    index=rfm_transformed.index
)

In [72]:
rfm_scaled.describe()

            Recency     Frequency      Monetary
count  5.862000e+03  5.862000e+03  5.862000e+03
mean   5.212101e-17  8.727239e-17 -3.587865e-16
std    1.000085e+00  1.000085e+00  1.000085e+00
min   -2.410328e+00 -1.056164e+00 -3.926931e+00
25%   -7.410944e-01 -1.056164e+00 -7.063467e-01
50%    7.578772e-02 -1.985183e-01 -3.800419e-02
75%    9.548480e-01  6.591275e-01  6.566805e-01
max    1.382294e+00  5.436090e+00  4.675981e+00

After log-transforming RFM features, I applied standardization so that recency, frequency, and monetary contributed equally to distance-based clustering

## 🔹 PHASE 1: Customer Segmentation (Unsupervised)

### 1️⃣ K-Means clustering (primary)

* Run K-Means for K = 2…10
* Compute:

  * Inertia (Elbow method)
  * Silhouette score

---

### 2️⃣ Select optimal K

* Choose K with:

  * Clear elbow
  * Highest / stable silhouette score

---

### 3️⃣ Train final K-Means model

* Fit K-Means with chosen K
* Assign cluster labels to customers

---

### 4️⃣ Evaluate K-Means clustering

* Silhouette score
* Cluster size distribution

---

### 5️⃣ Interpret clusters (business validation)

* Compute mean RFM per cluster
* Label clusters (e.g., Loyal, At-Risk, Churned)

---

### 6️⃣ Hierarchical clustering (validation)

* Fit Agglomerative clustering with same K
* Compare:

  * Silhouette score
  * Cluster structure vs K-Means

---
## 🔹 PHASE 2: Churn Definition

### 8️⃣ Define churn rule

* Example: No purchase in last **180 days**

---

### 9️⃣ Create churn label

* Binary target variable (0 = active, 1 = churned)

---

### 🔹 PHASE 3: Churn Modeling (Supervised)

### 🔟 Prepare churn dataset

* Features: `rfm_scaled`
* Target: churn label

---

### 1️⃣1️⃣ Train Logistic Regression (baseline)

* Fit model
* Predict churn probability

---

### 1️⃣2️⃣ Evaluate Logistic Regression

* ROC-AUC
* Recall (churn class)
* Confusion matrix

---

### 1️⃣3️⃣ Train Random Forest

* Fit model
* Predict churn probability

---

### 1️⃣4️⃣ Evaluate Random Forest

* ROC-AUC
* Recall
* Feature importance

---

### 1️⃣5️⃣ Train XGBoost

* Fit model
* Predict churn probability

---

### 1️⃣6️⃣ Evaluate XGBoost

* ROC-AUC
* Recall
* Precision-Recall tradeoff

---

### 1️⃣8️⃣ Select final churn model

* Choose based on:

  * Business goal (catch churners vs false alarms)
  * Model complexity

---

## 🔹 PHASE 5: Combined Insights

### 1️⃣9️⃣ Combine segmentation + churn

* Identify **high-value customers at churn risk**

---

### 2️⃣0️⃣ Business recommendations

* Retention strategies per segment

---